[package]
name = "bls_n_cws"
version = "0.1.0"
authors = ["caleb <bargercj20@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
